-- dropschema.sql

DROP VIEW IF EXISTS CandidatesForAllApplications CASCADE;
DROP VIEW IF EXISTS JobDetailsByDepartment CASCADE;
DROP TABLE IF EXISTS Departments CASCADE;
DROP TABLE IF EXISTS Letters CASCADE;
DROP TABLE IF EXISTS Applications CASCADE;
DROP TABLE IF EXISTS Jobs CASCADE;
DROP TABLE IF EXISTS Candidates CASCADE;
